version: 2.1

jobs:
  build:    
    working_directory: ~/app
    docker:
      - image: circleci/node:lts
    environment:
      NO_UPDATE_NOTIFIER: 1
      NODE_NO_WARNINGS: 1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-npm{{ checksum "package.json" }}
      - run:
          name: set log level
          command: npm config set loglevel warn
      - run:
          name: npm ci
          command: npm ci
      - run:
          name: npm run ensure-env
          command: npm run ensure-env
      - save_cache:
          key: dependency-cache-npm{{ checksum "package.json" }}
          paths:
            - ~/.npm
      - persist_to_workspace:
          root: ~/
          paths:
            - app
            
  lint_javascript:
    working_directory: ~/app
    docker:
      - image: circleci/node:lts
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: lint
          command: npm run lint
          
  unit_and_integration_tests:
    environment:
      LC_ALL: c.UTF-8
      LANG: c.UTF-8
    working_directory: ~/app
    docker:
      - image: circleci/node:lts
    steps:
      - attach_workspace:
          at: ~/        
      - run:
          name: set log level
          command: npm config set loglevel warn
      - run:
          name: npm ci
          command: npm ci
      - run:
          name: npm run ensure-env
          command: npm run ensure-env
      - run:
          name: test
          command: npm test
        
workflows:
  version: 2
  build_and_test:
    jobs:   
      - build
      - lint_javascript:
          requires:
            - build
      - unit_and_integration_tests:
          requires:
            - build
